### ISSUE TITLE
Inquiry about ParametricModels

### ISSUE THREAD

**Issue by jonghwanP** [Mohamedelrefaie/DrivAerNet#8]
I read the paper, and the data is very interesting.
Before treating 3D models, I want to check the tabular parametric data (design parameters, Average Cd...).

In ParametricModels,
combined_data.csv includes 3747 data, where the total number of data DrivAerNet++ is 8000.
Is there any plan to update this tabular parametric data?

Thanks.

**Comment by Mohamedelrefaie** [comment]
Hi @jonghwanP,

Thank you for your positive feedback on our paper and data!

Yes, for the parametric study, we used only about 4k designs. To standardize the parametric studies, we focused on 26 parameters instead of 50. The 50 geometric parameters model from the DrivAerNet paper (DrivAerNet V1) was based only on one car category, specifically the fastback, with a detailed underbody and open wheels. The choice of a 4k parametric design study was motivated to avoid data imbalance and to be able to compare different car designs (fastback vs estateback and notchback).

Please refer to Section 5.1.2, "_Aerodynamic drag prediction from tabular parametric data,_" in our paper for a more detailed description of this test case.

**Comment by jonghwanP** [comment]
Thanks for the reply.

I have another questions for the parametric table data.

1. Could you share the values of base design parameters for the fastback,
notchback, and estateback?
    In your paper,  there are min and max values (Table 4), but there is no
information about base parameter values for the DrivAer models.

2. For the wheel design variation (WW, WWC, WWS),
    what is the meaning of S? is it for the tire surface or wheel?
    (in paper, WW: with open wheels detailed, WWC: with wheels closed, WWS:
with open wheels smooth).
    For WWC (with wheels closed), is it smooth or detailed tire (or wheel)?

Sincerely,
